export const workouts = [
  {
    name: "45 min HIIT",
    category: "running",
    type: "hiit",
    duration: 45,
    level: 3,
    sets: [
      {
        name: "Intro",
        steps: [
          { duration: 60, speed: 4, legend: "Walk" },
          { duration: 60, speed: 7.2, legend: "Soft Run" },
        ],
      },
      {
        name: "Hill",
        steps: [
          { duration: 60, speed: 4.8, legend: "Rest" },
          { duration: 60, speed: 8.9, legend: "Run" },
          { duration: 60, speed: 4.8, legend: "Rest" },
          { duration: 90, speed: 8.9, legend: "Run" },
          { duration: 60, speed: 4.8, legend: "Rest" },
          { duration: 120, speed: 8.9, legend: "Run" },
          { duration: 60, speed: 4.8, legend: "Rest" },
          { duration: 90, speed: 8.9, legend: "Run" },
          { duration: 60, speed: 4.8, legend: "Rest" },
          { duration: 60, speed: 8.9, legend: "Run" },
        ],
      },
      {
        name: "HIIT",
        steps: [
          { duration: 60, speed: 4.8, legend: "Rest" },
          { duration: 60, speed: 9.7, legend: "Fast Run" },
          { duration: 30, speed: 4.8, legend: "Rest" },
          { duration: 60, speed: 9.9, legend: "Fast Run" },
          { duration: 30, speed: 4.8, legend: "Rest" },
          { duration: 60, speed: 10.1, legend: "Fast Run" },
          { duration: 30, speed: 4.8, legend: "Rest" },
          { duration: 60, speed: 10.3, legend: "Fast Run" },
          { duration: 30, speed: 4.8, legend: "Rest" },
          { duration: 60, speed: 10.5, legend: "Fast Run" },
          { duration: 30, speed: 4.8, legend: "Rest" },
          { duration: 60, speed: 10.7, legend: "Fast Run" },
          { duration: 30, speed: 4.8, legend: "Rest" },
          { duration: 60, speed: 10.9, legend: "Fast Run" },
          { duration: 30, speed: 4.8, legend: "Rest" },
          { duration: 60, speed: 11.1, legend: "Fast Run" },
          { duration: 30, speed: 4.8, legend: "Rest" },
          { duration: 60, speed: 11.3, legend: "Fast Run" },
          { duration: 30, speed: 4.8, legend: "Rest" },
          { duration: 60, speed: 11.5, legend: "Fast Run" },
        ],
      },
      {
        name: "Endurance",
        steps: [
          { duration: 60, speed: 4.8, legend: "Rest" },
          { duration: 180, speed: 8.9, legend: "Run" },
          { duration: 30, speed: 4.8, legend: "Rest" },
          { duration: 120, speed: 9.1, legend: "Run" },
          { duration: 30, speed: 4.8, legend: "Rest" },
          { duration: 90, speed: 9.3, legend: "Run" },
          { duration: 30, speed: 4.8, legend: "Rest" },
          { duration: 60, speed: 9.5, legend: "Run" },
          { duration: 30, speed: 4.8, legend: "Rest" },
          { duration: 30, speed: 9.7, legend: "Run" },
        ],
      },
      {
        name: "Cool Down",
        steps: [
          { duration: 60, speed: 4.8, legend: "Rest" },
          { duration: 60, speed: 7.2, legend: "Soft Run" },
          { duration: 60, speed: 4.8, legend: "Rest" },
          { duration: 60, speed: 4.0, legend: "Walk" },
        ],
      },
    ],
  },
  {
    name: "45 min Progression Run",
    category: "running",
    type: "hiit",
    duration: 45,
    level: 4,
    sets: [
      {
        name: "Intro",
        steps: [
          { duration: 60, speed: 4.8, legend: "Walk" },
          { duration: 120, speed: 7.2, legend: "Soft Run" },
          { duration: 60, speed: 4.8, legend: "Rest" },
        ],
      },
      {
        name: "Progression 1",
        steps: [
          { duration: 120, speed: 7.2, legend: "Soft Run" },
          { duration: 120, speed: 8, legend: "Run" },
          { duration: 120, speed: 8.9, legend: "Run" },
          { duration: 120, speed: 9.7, legend: "Fast Run" },
          { duration: 120, speed: 10.5, legend: "Fast Run" },
          { duration: 120, speed: 11.3, legend: "Fast Run" },
          { duration: 60, speed: 4.8, legend: "Rest" },
        ],
      },
      {
        name: "Progression 2",
        steps: [
          { duration: 120, speed: 7.2, legend: "Soft Run" },
          { duration: 120, speed: 8, legend: "Run" },
          { duration: 120, speed: 8.9, legend: "Run" },
          { duration: 120, speed: 9.7, legend: "Fast Run" },
          { duration: 120, speed: 10.5, legend: "Fast Run" },
          { duration: 120, speed: 11.3, legend: "Fast Run" },
          { duration: 60, speed: 4.8, legend: "Rest" },
        ],
      },
      {
        name: "Progression 3",
        steps: [
          { duration: 120, speed: 7.2, legend: "Soft Run" },
          { duration: 120, speed: 8, legend: "Run" },
          { duration: 120, speed: 8.9, legend: "Run" },
          { duration: 120, speed: 9.7, legend: "Fast Run" },
          { duration: 120, speed: 10.5, legend: "Fast Run" },
          { duration: 120, speed: 11.3, legend: "Fast Run" },
          { duration: 60, speed: 4.8, legend: "Rest" },
        ],
      },
      {
        name: "Cool Down",
        steps: [
          { duration: 120, speed: 7.2, legend: "Soft Run" },
          { duration: 60, speed: 4.8, legend: "Rest" },
          { duration: 60, speed: 4.0, legend: "Walk" },
        ],
      },
    ],
  },
  {
    name: "1 Hour Interval Burn Run",
    category: "running",
    type: "hiit",
    duration: 60,
    level: 5,
    sets: [
      {
        name: "Warm Up",
        steps: [
          { duration: 60, speed: 4.0, legend: "Walk" },
          { duration: 180, speed: 7.2, legend: "Soft Run" },
          { duration: 60, speed: 4.8, legend: "Rest" },
        ],
      },
      {
        name: "4-3-2-1 Intervals",
        steps: [
          { duration: 240, speed: 7.1, legend: "Soft Run" },
          { duration: 60, speed: 4.8, legend: "Rest" },
          { duration: 180, speed: 7.4, legend: "Soft Run" },
          { duration: 60, speed: 4.8, legend: "Rest" },
          { duration: 120, speed: 7.7, legend: "Soft Run" },
          { duration: 60, speed: 4.8, legend: "Rest" },
          { duration: 60, speed: 8.0, legend: "Run" },
          { duration: 60, speed: 4.8, legend: "Rest" },
          { duration: 60, speed: 7.2, legend: "Soft Run" },
        ],
      },
      {
        name: "2:1 HIIT",
        steps: [
          { duration: 120, speed: 8.0, legend: "Run" },
          { duration: 60, speed: 4.8, legend: "Rest" },
          { duration: 120, speed: 8.0, legend: "Run" },
          { duration: 60, speed: 4.8, legend: "Rest" },
          { duration: 120, speed: 8.0, legend: "Run" },
          { duration: 60, speed: 4.8, legend: "Rest" },
          { duration: 120, speed: 8.0, legend: "Run" },
          { duration: 60, speed: 4.8, legend: "Rest" },
          { duration: 120, speed: 8.0, legend: "Run" },
          { duration: 60, speed: 4.8, legend: "Rest" },
        ],
      },
      {
        name: "Long Intervals",
        steps: [
          { duration: 300, speed: 7.2, legend: "Soft Run" },
          { duration: 60, speed: 4.8, legend: "Rest" },
          { duration: 180, speed: 8.0, legend: "Run" },
          { duration: 60, speed: 4.8, legend: "Rest" },
          { duration: 60, speed: 8.9, legend: "Run" },
          { duration: 60, speed: 4.8, legend: "Rest" },
        ],
      },
      {
        name: "Boost Block",
        steps: [
          { duration: 90, speed: 8.0, legend: "Run" },
          { duration: 30, speed: 9.7, legend: "Fast Run" },
          { duration: 60, speed: 4.8, legend: "Rest" },
          { duration: 90, speed: 8.0, legend: "Run" },
          { duration: 30, speed: 9.7, legend: "Fast Run" },
          { duration: 60, speed: 4.8, legend: "Rest" },
          { duration: 90, speed: 8.0, legend: "Run" },
          { duration: 30, speed: 9.7, legend: "Fast Run" },
          { duration: 60, speed: 4.8, legend: "Rest" },
          { duration: 90, speed: 8.0, legend: "Run" },
          { duration: 30, speed: 9.7, legend: "Fast Run" },
        ],
      },
      {
        name: "Cool Down",
        steps: [
          { duration: 60, speed: 4.8, legend: "Rest" },
          { duration: 60, speed: 4.0, legend: "Walk" },
        ],
      },
    ],
  },
  {
    name: "30 min HIIT",
    category: "running",
    type: "hiit",
    duration: 30,
    level: 2,
    sets: [
      {
        name: "Intro",
        steps: [
          { duration: 60, speed: 4.0, legend: "Walk" },
          { duration: 180, speed: 8.0, legend: "Soft Run" },
        ],
      },
      {
        name: "HIIT",
        steps: [
          { duration: 60, speed: 4.8, legend: "Rest" },
          { duration: 60, speed: 8.0, legend: "Run" },
          { duration: 60, speed: 4.8, legend: "Rest" },
          { duration: 60, speed: 8.2, legend: "Run" },
          { duration: 60, speed: 4.8, legend: "Rest" },
          { duration: 60, speed: 8.4, legend: "Run" },
          { duration: 60, speed: 4.8, legend: "Rest" },
          { duration: 60, speed: 8.6, legend: "Run" },
          { duration: 60, speed: 4.8, legend: "Rest" },
          { duration: 60, speed: 8.8, legend: "Run" },
          { duration: 60, speed: 4.8, legend: "Rest" },
          { duration: 60, speed: 9.0, legend: "Run" },
          { duration: 60, speed: 4.8, legend: "Rest" },
          { duration: 60, speed: 9.2, legend: "Run" },
          { duration: 60, speed: 4.8, legend: "Rest" },
          { duration: 60, speed: 9.4, legend: "Run" },
        ],
      },
      {
        name: "Endurance",
        steps: [
          { duration: 60, speed: 4.8, legend: "Rest" },
          { duration: 180, speed: 8.0, legend: "Run" },
          { duration: 60, speed: 4.8, legend: "Rest" },
          { duration: 180, speed: 8.0, legend: "Run" },
        ],
      },
      {
        name: "Cool Down",
        steps: [
          { duration: 60, speed: 4.8, legend: "Rest" },
          { duration: 60, speed: 7.0, legend: "Run" },
          { duration: 60, speed: 4.0, legend: "Walk" },
        ],
      },
    ],
  },
];
